const carBrands = [
    { value: "toyota", label: "Toyota" },
    { value: "lada", label: "Lada (ВАЗ)" },
    { value: "hyundai", label: "Hyundai" },
    { value: "kia", label: "Kia" },
    { value: "chevrolet", label: "Chevrolet" },
    { value: "nissan", label: "Nissan" },
    { value: "volkswagen", label: "Volkswagen" },
    { value: "skoda", label: "Skoda" },
    { value: "renault", label: "Renault" },
    { value: "mercedes-benz", label: "Mercedes-Benz" },
    { value: "bmw", label: "BMW" },
    { value: "audi", label: "Audi" },
    { value: "ford", label: "Ford" },
    { value: "mazda", label: "Mazda" },
    { value: "honda", label: "Honda" },
    { value: "mitsubishi", label: "Mitsubishi" },
    { value: "lexus", label: "Lexus" },
    { value: "peugeot", label: "Peugeot" },
    { value: "citroen", label: "Citroen" },
    { value: "land-rover", label: "Land Rover" },
    { value: "jeep", label: "Jeep" },
    { value: "subaru", label: "Subaru" },
    { value: "volvo", label: "Volvo" },
    { value: "infiniti", label: "Infiniti" },
    { value: "tesla", label: "Tesla" },
    { value: "ssangyong", label: "SsangYong" },
    { value: "porsche", label: "Porsche" },
    { value: "jaguar", label: "Jaguar" },
    { value: "fiat", label: "Fiat" },
    { value: "alfa-romeo", label: "Alfa Romeo" },
    { value: "maserati", label: "Maserati" },
    { value: "bentley", label: "Bentley" },
    { value: "rolls-royce", label: "Rolls-Royce" },
    { value: "lotus", label: "Lotus" },
    { value: "mini", label: "MINI" },
    { value: "cadillac", label: "Cadillac" },
    { value: "buick", label: "Buick" },
    { value: "chrysler", label: "Chrysler" },
    { value: "lincoln", label: "Lincoln" },
    { value: "dodge", label: "Dodge" },
    { value: "ram", label: "RAM" },
    { value: "aston-martin", label: "Aston Martin" },
    { value: "volkswagen", label: "Volkswagen" },
    { value: "land-rover", label: "Land Rover" },
    { value: "maybach", label: "Maybach" },
    { value: "ferrari", label: "Ferrari" },
    { value: "lamborghini", label: "Lamborghini" },
    { value: "morgan", label: "Morgan" },
    { value: "saab", label: "Saab" },
    { value: "smart", label: "Smart" },
    { value: "dacia", label: "Dacia" },
    { value: "geely", label: "Geely" },
    { value: "byd", label: "BYD" },
    { value: "great-wall", label: "Great Wall" },
    { value: "changan", label: "Changan" },
    { value: "zotye", label: "Zotye" },
    { value: "dongfeng", label: "Dongfeng" },
    { value: "jac", label: "JAC" },
    // Добавьте дополнительные марки по аналогии
];

export default carBrands;
